// const button = document.querySelector('button').addEventListener('click')

// const siteSelect = chrome.tabs.query({active: true, lastFocusedWindow: true}, tabs => {
//     let url = tabs[0].url;
//     alert(url)
//     console.log(url)
// });

//creates an object store of indexes with cohort names
const cohortGenerator = () => {
  const cohortNames = ['Emil M.', 'Murad A.', 'Emily B.', 'Eli M.', 'Hui M.', 'Dzidupe E.', 'Irvin I.', 'David J.', 'Jackie M.', 'Crystal A.', 'Jason C', 'Mander M.', 'Jeff W.', 'Chris J.', 'Johnny T.', 'Chase W.', 'Eden E.', 'Nick K.', 'Katie A.', 'Ben R.', 'Kevin L.', 'Alyssa C.', 'Mimi L.', 'Will M.', 'Richard Z.', 'Tyler W.', 'Rosendo D.L.', 'Andrew J.', 'Samee V.', 'Samson L.'];
  let cohortObjStore = {};
  for (let i = 0; i < cohortNames.length; i++){
    cohortObjStore[i+1] = cohortNames[i];
  }
  return cohortObjStore;
}

//Re-assigns name in YogaInstructor element randomly
function generateName () {
    //obj store of indexes to cohort names 
    const ftri10 = cohortGenerator();
    //change inner Text of YogaInstructor
    console.log(document.querySelector('#YogaInstructor'))
    document.querySelector('#YogaInstructor').textContent = `Today's Yogi: ${ftri10[Math.floor(Math.random() * Object.keys(ftri10).length)]}`
    
    // yoga.appendChild
}

//Re-assigns colors on each button
const randomizeColors = () =>{
  const colors = [
    'Black',
    'Navy',
    'DarkBlue',
    'MediumBlue',
    'Blue',
    'DarkGreen',
    'Green',
    'Teal',
    'DarkCyan',
    'DeepSkyBlue',
    'DarkTurquoise',
    'MediumSpringGreen',
    'Lime',
    'SpringGreen',
    'Aqua',
    'Cyan',
    'MidnightBlue',
    'DodgerBlue',
    'LightSeaGreen',
    'ForestGreen',
    'SeaGreen',
    'DarkSlateGray',
    'LimeGreen',
    'MediumSeaGreen',
    'Turquoise',
    'RoyalBlue',
    'SteelBlue',
    'DarkSlateBlue',
    'MediumTurquoise',
    'Indigo',
    'DarkOliveGreen',
    'CadetBlue',
    'CornflowerBlue',
    'RebeccaPurple',
    'MediumAquaMarine',
    'DimGray',
    'SlateBlue',
    'OliveDrab',
    'SlateGray',
    'LightSlateGray',
    'MediumSlateBlue',
    'LawnGreen',
    'Chartreuse',
    'Aquamarine',
    'Maroon',
    'Purple',
    'Olive',
    'Gray',
    'SkyBlue',
    'LightSkyBlue',
    'BlueViolet',
    'DarkRed',
    'DarkMagenta',
    'SaddleBrown',
    'DarkSeaGreen',
    'LightGreen',
    'MediumPurple',
    'DarkViolet',
    'PaleGreen',
    'DarkOrchid',
    'YellowGreen',
    'Sienna',
    'Brown',
    'DarkGray',
    'LightBlue',
    'GreenYellow',
    'PaleTurquoise',
    'LightSteelBlue',
    'PowderBlue',
    'FireBrick',
    'DarkGoldenRod',
    'MediumOrchid',
    'RosyBrown',
    'DarkKhaki',
    'Silver',
    'MediumVioletRed',
    'IndianRed',
    'Peru',
    'Chocolate',
    'Tan',
    'LightGray',
    'Thistle',
    'Orchid',
    'GoldenRod',
    'PaleVioletRed',
    'Crimson',
    'Gainsboro',
    'Plum',
    'BurlyWood',
    'LightCyan',
    'Lavender',
    'DarkSalmon',
    'Violet',
    'PaleGoldenRod',
    'LightCoral',
    'Khaki',
    'AliceBlue',
    'HoneyDew',
    'Azure',
    'SandyBrown',
    'Wheat',
    'Beige',
    'WhiteSmoke',
    'MintCream',
    'GhostWhite',
    'Salmon',
    'AntiqueWhite',
    'Linen',
    'LightGoldenRodYellow',
    'OldLace',
    'Red',
    'Fuchsia',
    'Magenta',
    'DeepPink',
    'OrangeRed',
    'Tomato',
    'HotPink',
    'Coral',
    'DarkOrange',
    'LightSalmon',
    'Orange',
    'LightPink',
    'Pink',
    'Gold',
    'PeachPuff',
    'NavajoWhite',
    'Moccasin',
    'Bisque',
    'MistyRose',
    'BlanchedAlmond',
    'PapayaWhip',
    'LavenderBlush',
    'SeaShell',
    'Cornsilk',
    'LemonChiffon',
    'FloralWhite',
    'Snow',
    'Yellow',
    'LightYellow',
    'Ivory',
    'White',
  ];
  
  //use math.random to 
  const allBoxes = document.querySelectorAll('.square')
  console.log(allBoxes)
  allBoxes.forEach((box) => {
    box.style.backgroundColor = colors[Math.floor(Math.random()* colors.length)];
  })

}

//EventHandler that will invoke generateName and randomizeColors //setInterval and clearInterval to make shuffling effect
document.querySelector('#stretchGetButton').addEventListener(
    'click', () => {
       
        console.log('button works')
        for (let i = 0; i < 30; i++){
        const generateNameInterval = setInterval(()=>{generateName()}, 10);
        const randomizeColorsInterval = setInterval(()=>{randomizeColors()}, 300);
        setTimeout(() => {clearInterval(generateNameInterval)}, 3000);
        setTimeout(() => {clearInterval(randomizeColorsInterval)}, 3000);
        }
        
        // clearInterval(randomizeColorsInterval);
        
    })




    // const colors = [
    //     'Black',
    //     'Navy',
    //     'DarkBlue',
    //     'MediumBlue',
    //     'Blue',
    //     'DarkGreen',
    //     'Green',
    //     'Teal',
    //     'DarkCyan',
    //     'DeepSkyBlue',
    //     'DarkTurquoise',
    //     'MediumSpringGreen',
    //     'Lime',
    //     'SpringGreen',
    //     'Aqua',
    //     'Cyan',
    //     'MidnightBlue',
    //     'DodgerBlue',
    //     'LightSeaGreen',
    //     'ForestGreen',
    //     'SeaGreen',
    //     'DarkSlateGray',
    //     'LimeGreen',
    //     'MediumSeaGreen',
    //     'Turquoise',
    //     'RoyalBlue',
    //     'SteelBlue',
    //     'DarkSlateBlue',
    //     'MediumTurquoise',
    //     'Indigo',
    //     'DarkOliveGreen',
    //     'CadetBlue',
    //     'CornflowerBlue',
    //     'RebeccaPurple',
    //     'MediumAquaMarine',
    //     'DimGray',
    //     'SlateBlue',
    //     'OliveDrab',
    //     'SlateGray',
    //     'LightSlateGray',
    //     'MediumSlateBlue',
    //     'LawnGreen',
    //     'Chartreuse',
    //     'Aquamarine',
    //     'Maroon',
    //     'Purple',
    //     'Olive',
    //     'Gray',
    //     'SkyBlue',
    //     'LightSkyBlue',
    //     'BlueViolet',
    //     'DarkRed',
    //     'DarkMagenta',
    //     'SaddleBrown',
    //     'DarkSeaGreen',
    //     'LightGreen',
    //     'MediumPurple',
    //     'DarkViolet',
    //     'PaleGreen',
    //     'DarkOrchid',
    //     'YellowGreen',
    //     'Sienna',
    //     'Brown',
    //     'DarkGray',
    //     'LightBlue',
    //     'GreenYellow',
    //     'PaleTurquoise',
    //     'LightSteelBlue',
    //     'PowderBlue',
    //     'FireBrick',
    //     'DarkGoldenRod',
    //     'MediumOrchid',
    //     'RosyBrown',
    //     'DarkKhaki',
    //     'Silver',
    //     'MediumVioletRed',
    //     'IndianRed',
    //     'Peru',
    //     'Chocolate',
    //     'Tan',
    //     'LightGray',
    //     'Thistle',
    //     'Orchid',
    //     'GoldenRod',
    //     'PaleVioletRed',
    //     'Crimson',
    //     'Gainsboro',
    //     'Plum',
    //     'BurlyWood',
    //     'LightCyan',
    //     'Lavender',
    //     'DarkSalmon',
    //     'Violet',
    //     'PaleGoldenRod',
    //     'LightCoral',
    //     'Khaki',
    //     'AliceBlue',
    //     'HoneyDew',
    //     'Azure',
    //     'SandyBrown',
    //     'Wheat',
    //     'Beige',
    //     'WhiteSmoke',
    //     'MintCream',
    //     'GhostWhite',
    //     'Salmon',
    //     'AntiqueWhite',
    //     'Linen',
    //     'LightGoldenRodYellow',
    //     'OldLace',
    //     'Red',
    //     'Fuchsia',
    //     'Magenta',
    //     'DeepPink',
    //     'OrangeRed',
    //     'Tomato',
    //     'HotPink',
    //     'Coral',
    //     'DarkOrange',
    //     'LightSalmon',
    //     'Orange',
    //     'LightPink',
    //     'Pink',
    //     'Gold',
    //     'PeachPuff',
    //     'NavajoWhite',
    //     'Moccasin',
    //     'Bisque',
    //     'MistyRose',
    //     'BlanchedAlmond',
    //     'PapayaWhip',
    //     'LavenderBlush',
    //     'SeaShell',
    //     'Cornsilk',
    //     'LemonChiffon',
    //     'FloralWhite',
    //     'Snow',
    //     'Yellow',
    //     'LightYellow',
    //     'Ivory',
    //     'White',
    //   ];